# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import music_pb2 as music__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in music_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub:
    """── Service ──────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/music.MusicService/ListUsers',
                request_serializer=music__pb2.Empty.SerializeToString,
                response_deserializer=music__pb2.UserList.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/music.MusicService/GetUser',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/music.MusicService/CreateUser',
                request_serializer=music__pb2.CreateUserReq.SerializeToString,
                response_deserializer=music__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/music.MusicService/UpdateUser',
                request_serializer=music__pb2.UpdateUserReq.SerializeToString,
                response_deserializer=music__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/music.MusicService/DeleteUser',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.Empty.FromString,
                _registered_method=True)
        self.ListSongs = channel.unary_unary(
                '/music.MusicService/ListSongs',
                request_serializer=music__pb2.Empty.SerializeToString,
                response_deserializer=music__pb2.SongList.FromString,
                _registered_method=True)
        self.GetSong = channel.unary_unary(
                '/music.MusicService/GetSong',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.Song.FromString,
                _registered_method=True)
        self.CreateSong = channel.unary_unary(
                '/music.MusicService/CreateSong',
                request_serializer=music__pb2.CreateSongReq.SerializeToString,
                response_deserializer=music__pb2.Song.FromString,
                _registered_method=True)
        self.UpdateSong = channel.unary_unary(
                '/music.MusicService/UpdateSong',
                request_serializer=music__pb2.UpdateSongReq.SerializeToString,
                response_deserializer=music__pb2.Song.FromString,
                _registered_method=True)
        self.DeleteSong = channel.unary_unary(
                '/music.MusicService/DeleteSong',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.Empty.FromString,
                _registered_method=True)
        self.ListPlaylists = channel.unary_unary(
                '/music.MusicService/ListPlaylists',
                request_serializer=music__pb2.Empty.SerializeToString,
                response_deserializer=music__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.GetPlaylist = channel.unary_unary(
                '/music.MusicService/GetPlaylist',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.Playlist.FromString,
                _registered_method=True)
        self.ListPlaylistsByUser = channel.unary_unary(
                '/music.MusicService/ListPlaylistsByUser',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.CreatePlaylist = channel.unary_unary(
                '/music.MusicService/CreatePlaylist',
                request_serializer=music__pb2.CreatePlaylistReq.SerializeToString,
                response_deserializer=music__pb2.Playlist.FromString,
                _registered_method=True)
        self.UpdatePlaylist = channel.unary_unary(
                '/music.MusicService/UpdatePlaylist',
                request_serializer=music__pb2.UpdatePlaylistReq.SerializeToString,
                response_deserializer=music__pb2.Playlist.FromString,
                _registered_method=True)
        self.DeletePlaylist = channel.unary_unary(
                '/music.MusicService/DeletePlaylist',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPlaylistSongs = channel.unary_unary(
                '/music.MusicService/GetPlaylistSongs',
                request_serializer=music__pb2.IdRequest.SerializeToString,
                response_deserializer=music__pb2.SongList.FromString,
                _registered_method=True)
        self.AddSongToPlaylist = channel.unary_unary(
                '/music.MusicService/AddSongToPlaylist',
                request_serializer=music__pb2.PlaylistSongReq.SerializeToString,
                response_deserializer=music__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveSongFromPlaylist = channel.unary_unary(
                '/music.MusicService/RemoveSongFromPlaylist',
                request_serializer=music__pb2.PlaylistSongReq.SerializeToString,
                response_deserializer=music__pb2.Empty.FromString,
                _registered_method=True)


class MusicServiceServicer:
    """── Service ──────────────────────────────────────────────────
    """

    def ListUsers(self, request, context):
        """Users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSongs(self, request, context):
        """Songs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylists(self, request, context):
        """Playlists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylistsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSongToPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSongFromPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=music__pb2.Empty.FromString,
                    response_serializer=music__pb2.UserList.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=music__pb2.CreateUserReq.FromString,
                    response_serializer=music__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=music__pb2.UpdateUserReq.FromString,
                    response_serializer=music__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.Empty.SerializeToString,
            ),
            'ListSongs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSongs,
                    request_deserializer=music__pb2.Empty.FromString,
                    response_serializer=music__pb2.SongList.SerializeToString,
            ),
            'GetSong': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSong,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.Song.SerializeToString,
            ),
            'CreateSong': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSong,
                    request_deserializer=music__pb2.CreateSongReq.FromString,
                    response_serializer=music__pb2.Song.SerializeToString,
            ),
            'UpdateSong': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSong,
                    request_deserializer=music__pb2.UpdateSongReq.FromString,
                    response_serializer=music__pb2.Song.SerializeToString,
            ),
            'DeleteSong': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSong,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.Empty.SerializeToString,
            ),
            'ListPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylists,
                    request_deserializer=music__pb2.Empty.FromString,
                    response_serializer=music__pb2.PlaylistList.SerializeToString,
            ),
            'GetPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylist,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.Playlist.SerializeToString,
            ),
            'ListPlaylistsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylistsByUser,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.PlaylistList.SerializeToString,
            ),
            'CreatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylist,
                    request_deserializer=music__pb2.CreatePlaylistReq.FromString,
                    response_serializer=music__pb2.Playlist.SerializeToString,
            ),
            'UpdatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlaylist,
                    request_deserializer=music__pb2.UpdatePlaylistReq.FromString,
                    response_serializer=music__pb2.Playlist.SerializeToString,
            ),
            'DeletePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylist,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.Empty.SerializeToString,
            ),
            'GetPlaylistSongs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistSongs,
                    request_deserializer=music__pb2.IdRequest.FromString,
                    response_serializer=music__pb2.SongList.SerializeToString,
            ),
            'AddSongToPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSongToPlaylist,
                    request_deserializer=music__pb2.PlaylistSongReq.FromString,
                    response_serializer=music__pb2.Empty.SerializeToString,
            ),
            'RemoveSongFromPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSongFromPlaylist,
                    request_deserializer=music__pb2.PlaylistSongReq.FromString,
                    response_serializer=music__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService:
    """── Service ──────────────────────────────────────────────────
    """

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/ListUsers',
            music__pb2.Empty.SerializeToString,
            music__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetUser',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/CreateUser',
            music__pb2.CreateUserReq.SerializeToString,
            music__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/UpdateUser',
            music__pb2.UpdateUserReq.SerializeToString,
            music__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/DeleteUser',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/ListSongs',
            music__pb2.Empty.SerializeToString,
            music__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetSong',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/CreateSong',
            music__pb2.CreateSongReq.SerializeToString,
            music__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/UpdateSong',
            music__pb2.UpdateSongReq.SerializeToString,
            music__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/DeleteSong',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/ListPlaylists',
            music__pb2.Empty.SerializeToString,
            music__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetPlaylist',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlaylistsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/ListPlaylistsByUser',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/CreatePlaylist',
            music__pb2.CreatePlaylistReq.SerializeToString,
            music__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/UpdatePlaylist',
            music__pb2.UpdatePlaylistReq.SerializeToString,
            music__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/DeletePlaylist',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetPlaylistSongs',
            music__pb2.IdRequest.SerializeToString,
            music__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSongToPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/AddSongToPlaylist',
            music__pb2.PlaylistSongReq.SerializeToString,
            music__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSongFromPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/RemoveSongFromPlaylist',
            music__pb2.PlaylistSongReq.SerializeToString,
            music__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
