import os, time
from concurrent import futures
import grpc
from sqlalchemy import create_engine, text

# Generated by protoc at Docker build time
import music_pb2
import music_pb2_grpc

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://music:music123@localhost:5432/musicdb")

def get_engine():
    for i in range(30):
        try:
            eng = create_engine(DATABASE_URL, pool_pre_ping=True)
            with eng.connect() as c: c.execute(text("SELECT 1"))
            print("DB connected!"); return eng
        except Exception as e:
            print(f"Waiting for DB ({i+1}/30): {e}"); time.sleep(2)
    raise RuntimeError("DB unavailable")

engine = get_engine()

SONG_SEL = ("SELECT id, title, artist, COALESCE(album,''), COALESCE(year,0), "
            "COALESCE(genre,''), COALESCE(duration_seconds,0), created_at")

# ── Servicer ──────────────────────────────────────────────────

class MusicServicer(music_pb2_grpc.MusicServiceServicer):

    def _u(self, r):
        return music_pb2.User(id=r[0], name=r[1], email=r[2], created_at=str(r[3]))

    def _s(self, r):
        return music_pb2.Song(id=r[0], title=r[1], artist=r[2], album=r[3] or "",
                              year=r[4] or 0, genre=r[5] or "",
                              duration_seconds=r[6] or 0, created_at=str(r[7]))

    def _p(self, r):
        return music_pb2.Playlist(id=r[0], user_id=r[1], name=r[2], created_at=str(r[3]))

    # ── Users ─────────────────────────────────────────────────

    def ListUsers(self, req, ctx):
        with engine.connect() as c:
            rows = c.execute(text("SELECT id,name,email,created_at FROM users ORDER BY id")).fetchall()
        return music_pb2.UserList(users=[self._u(r) for r in rows])

    def GetUser(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text("SELECT id,name,email,created_at FROM users WHERE id=:id"), {"id": req.id}).fetchone()
        if not r:
            ctx.set_code(grpc.StatusCode.NOT_FOUND)
            ctx.set_details("User not found")
            return music_pb2.User()
        return self._u(r)

    def CreateUser(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text("INSERT INTO users(name,email) VALUES(:n,:e) RETURNING id,name,email,created_at"),
                          {"n": req.name, "e": req.email}).fetchone()
            c.commit()
        return self._u(r)

    def UpdateUser(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text("UPDATE users SET name=:n,email=:e WHERE id=:id RETURNING id,name,email,created_at"),
                          {"n": req.name, "e": req.email, "id": req.id}).fetchone()
            c.commit()
        if not r:
            ctx.set_code(grpc.StatusCode.NOT_FOUND); return music_pb2.User()
        return self._u(r)

    def DeleteUser(self, req, ctx):
        with engine.connect() as c:
            c.execute(text("DELETE FROM users WHERE id=:id"), {"id": req.id}); c.commit()
        return music_pb2.Empty()

    # ── Songs ─────────────────────────────────────────────────

    def ListSongs(self, req, ctx):
        with engine.connect() as c:
            rows = c.execute(text(f"{SONG_SEL} FROM songs ORDER BY id")).fetchall()
        return music_pb2.SongList(songs=[self._s(r) for r in rows])

    def GetSong(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text(f"{SONG_SEL} FROM songs WHERE id=:id"), {"id": req.id}).fetchone()
        if not r:
            ctx.set_code(grpc.StatusCode.NOT_FOUND); ctx.set_details("Song not found")
            return music_pb2.Song()
        return self._s(r)

    def CreateSong(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text(
                f"INSERT INTO songs(title,artist,album,year,genre,duration_seconds) "
                f"VALUES(:t,:a,:al,:y,:g,:d) RETURNING {SONG_SEL.split('SELECT ')[1]}"),
                {"t": req.title, "a": req.artist, "al": req.album,
                 "y": req.year, "g": req.genre, "d": req.duration_seconds}).fetchone()
            c.commit()
        return self._s(r)

    def UpdateSong(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text(
                f"UPDATE songs SET title=:t,artist=:a,album=:al,year=:y,genre=:g,duration_seconds=:d "
                f"WHERE id=:id RETURNING {SONG_SEL.split('SELECT ')[1]}"),
                {"t": req.title, "a": req.artist, "al": req.album,
                 "y": req.year, "g": req.genre, "d": req.duration_seconds, "id": req.id}).fetchone()
            c.commit()
        if not r:
            ctx.set_code(grpc.StatusCode.NOT_FOUND); return music_pb2.Song()
        return self._s(r)

    def DeleteSong(self, req, ctx):
        with engine.connect() as c:
            c.execute(text("DELETE FROM songs WHERE id=:id"), {"id": req.id}); c.commit()
        return music_pb2.Empty()

    # ── Playlists ─────────────────────────────────────────────

    def ListPlaylists(self, req, ctx):
        with engine.connect() as c:
            rows = c.execute(text("SELECT id,user_id,name,created_at FROM playlists ORDER BY id")).fetchall()
        return music_pb2.PlaylistList(playlists=[self._p(r) for r in rows])

    def GetPlaylist(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text("SELECT id,user_id,name,created_at FROM playlists WHERE id=:id"), {"id": req.id}).fetchone()
        if not r:
            ctx.set_code(grpc.StatusCode.NOT_FOUND); return music_pb2.Playlist()
        return self._p(r)

    def ListPlaylistsByUser(self, req, ctx):
        with engine.connect() as c:
            rows = c.execute(text("SELECT id,user_id,name,created_at FROM playlists WHERE user_id=:uid ORDER BY id"), {"uid": req.id}).fetchall()
        return music_pb2.PlaylistList(playlists=[self._p(r) for r in rows])

    def CreatePlaylist(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text("INSERT INTO playlists(user_id,name) VALUES(:uid,:n) RETURNING id,user_id,name,created_at"),
                          {"uid": req.user_id, "n": req.name}).fetchone()
            c.commit()
        return self._p(r)

    def UpdatePlaylist(self, req, ctx):
        with engine.connect() as c:
            r = c.execute(text("UPDATE playlists SET name=:n WHERE id=:id RETURNING id,user_id,name,created_at"),
                          {"n": req.name, "id": req.id}).fetchone()
            c.commit()
        if not r:
            ctx.set_code(grpc.StatusCode.NOT_FOUND); return music_pb2.Playlist()
        return self._p(r)

    def DeletePlaylist(self, req, ctx):
        with engine.connect() as c:
            c.execute(text("DELETE FROM playlists WHERE id=:id"), {"id": req.id}); c.commit()
        return music_pb2.Empty()

    def GetPlaylistSongs(self, req, ctx):
        with engine.connect() as c:
            rows = c.execute(text(
                "SELECT s.id,s.title,s.artist,COALESCE(s.album,''),COALESCE(s.year,0),"
                "COALESCE(s.genre,''),COALESCE(s.duration_seconds,0),s.created_at "
                "FROM songs s JOIN playlist_songs ps ON s.id=ps.song_id "
                "WHERE ps.playlist_id=:pid ORDER BY s.id"), {"pid": req.id}).fetchall()
        return music_pb2.SongList(songs=[self._s(r) for r in rows])

    def AddSongToPlaylist(self, req, ctx):
        with engine.connect() as c:
            c.execute(text("INSERT INTO playlist_songs(playlist_id,song_id) VALUES(:pid,:sid) ON CONFLICT DO NOTHING"),
                      {"pid": req.playlist_id, "sid": req.song_id}); c.commit()
        return music_pb2.Empty()

    def RemoveSongFromPlaylist(self, req, ctx):
        with engine.connect() as c:
            c.execute(text("DELETE FROM playlist_songs WHERE playlist_id=:pid AND song_id=:sid"),
                      {"pid": req.playlist_id, "sid": req.song_id}); c.commit()
        return music_pb2.Empty()

# ── Server ────────────────────────────────────────────────────

if __name__ == "__main__":
    port = os.getenv("PORT", "8013")
    srv = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    music_pb2_grpc.add_MusicServiceServicer_to_server(MusicServicer(), srv)
    srv.add_insecure_port(f"[::]:{port}")
    srv.start()
    print(f"Python gRPC listening on :{port}")
    srv.wait_for_termination()
